apiVersion: v1
kind: Namespace
metadata:
  name: keyvault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvault-app-deploy
  namespace: keyvault
  labels:
    app: keyvault-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvault-app
  template:
    metadata:
      labels:
        app: keyvault-app
        aadpodidbinding: "keyvault-podidentity"
    spec:
      containers:
      - name: keyvault-app
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: kv-secret
              key: my-secret
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname"
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                   # accepted provider options: azure or vault
  parameters:
    usePodIdentity: "true"         # [OPTIONAL for Azure] if not provided, will default to "false"
    keyvaultName: "$kvName"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: my-secret
          objectType: secret
          objectAlias: secretalias
    resourceGroup: "$resourceGroup"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "$subscriptionId"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "$tenantId"                 # the tenant ID of the KeyVault
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: kv-secret
    type: Opaque
    data: 
    - objectName: secretalias                    # name of the mounted content to sync. this could be the object name or object alias 
      key: my-secret