apiVersion: v1
kind: Namespace
metadata:
  name: keyvault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvault-app
  namespace: keyvault
  labels:
    aadpodidbinding: keyvault-podidentity
    app: keyvault-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keyvault-app
  template:
    metadata:
      labels:
        app: keyvault-app
    spec:
      containers:
      - name: keyvault-app
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname"
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                   # accepted provider options: azure or vault
  parameters:
    usePodIdentity: "true"         # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: "false"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: "client_id"  # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: ""          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: my-secret
          objectType: secret
    resourceGroup: "rg-aks-test"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "6c9dc160-dca4-47cb-9e76-ed16a4b4edb1"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                 # the tenant ID of the KeyVault