apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: my-app-to-monitor
  name: my-app-to-monitor-svcmoni
  namespace: monitor
spec:
  endpoints:
  - interval: 15s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitor
  # This selector match service and not pod
  selector:
    matchLabels:
      app: my-app-to-monitor